site_name: CurveMaster (test)
# site_url: https://github.com/nikcrv/curvemaster/
repo_url: https://github.com/nikcrv/curvemaster
repo_name: GitHub
edit_uri: "edit/main/docs/"

theme:
  name: material
  language: ru
  icon:
    edit: material/pencil
  palette:
    # Светлая тема
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    # Темная тема  
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - navigation.instant
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.action.edit

docs_dir: docs

extra_javascript:
  - assets/chat-widget.js
  - assets/theme-switcher.js
  - https://cdn.jsdelivr.net/npm/d3@7/dist/d3.min.js
  - assets/projects-data.js
  - assets/ecosystem-map.js

nav:
  - Главная: index.md
  - Интерактивная карта: ecosystem-map.md
  - Протоколы экосистемы:
    - Curve Finance: projects/curve.md
    - Convex Finance: projects/convex.md
    - Yearn Finance: projects/yearn.md
    - Frax Finance: projects/frax.md
  - Ресурсы: resources.md
  - Боты: bots.md
  - Внести вклад: contribute.md
extra_css:
  - assets/custom-widget.css

site_dir: site
